languageCode = "en-us"
title = "Tarini"
baseurl = "http://example.org/"
theme = "prologue"

[params]
  name = "     Tarini Chandrashekhar"
  description = "Engineer,dancer,poet,speaker"
  copyright = "tarini"

[[params.social]]
medium = "instagram"
icon = "instagram"
link = "https://www.instagram.com/beentherepunthat/"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/tarini-chandrashekhar-79050772/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/tarini.chandrashekhar"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/tarini92"



# Portfolio column one

[[params.portfolio1]]
  title = "Hosting Yamini 2017 (A dawn to dusk classical event)"
  alt = ""
  source = "img/host.JPG"
  url = "#"

[[params.portfolio1]]
  title = "A Modern Classical Dance Fusion"
  alt = ""
  source = "img/dance.jpg"
  url = "https://youtu.be/B2GNlYATw6Q?t=705"

# Portfolio column two

[[params.portfolio2]]
  title = "Open mic at Dialogues cafe, Koramangala."
  alt = ""
  source = "img/dialogues.jpg"
  url = "https://www.youtube.com/watch?v=zfn96oVqPkc"

[[params.portfolio2]]
  title = "Laali Pooli"
  alt = ""
  source = "img/LPLogoInsta.jpg"
  url = "https://www.instagram.com/laalipooli/"

[[params.portfolio2]]
title = "Conducted a fun theatre workshop for a Hyderabad Government school"
alt = ""
source = "img/children.jpg"
url = "#"



# Portfolio column 3

[[params.portfolio3]]
  title = "The Way Out"
  alt = ""
  source = "img/wayout.JPG"
  url = "https://www.youtube.com/watch?v=ualpyf-3YCc"

[[params.portfolio3]]
  title = "Spreading awareness about the menstrual cups."
  alt = ""
  source = "img/menstrualcup.jpg"
  url = "https://www.instagram.com/p/B4RWio1gEqp/?utm_source=ig_web_copy_link"
